Template_DoAn_LTW/Controllers/DangKyController.cs
using System;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Template_DoAn_LTW.Controllers
{
    public class DangKyController : Controller
    {
        private QL_SachEntities ql = new QL_SachEntities();

        // GET: DangKy
        public ActionResult Index()
        {
            return View();
        }

        // POST: DangKy
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(
            string HoTen,
            string Email,
            string MatKhau,
            string SDT,
            string DiaChi,
            HttpPostedFileBase AnhDaiDienUpload)
        {
            if (ql.NguoiDungs.Any(x => x.Email == Email))
            {
                ViewBag.Error = "Email đã tồn tại!";
                return View();
            }
            string avatar = "default-avatar.jpg";
            if (AnhDaiDienUpload != null && AnhDaiDienUpload.ContentLength > 0)
            {
                var ext = Path.GetExtension(AnhDaiDienUpload.FileName).ToLower();
                string[] allowExt = { ".jpg", ".jpeg", ".png", ".webp" };

                if (!allowExt.Contains(ext))
                {
                    ViewBag.Error = "Chỉ cho phép ảnh jpg, png, webp";
                    return View();
                }

                avatar = Guid.NewGuid() + ext;
                string path = Path.Combine(Server.MapPath("~/Content/HinhAnh/"), avatar);
                AnhDaiDienUpload.SaveAs(path);
            }

            NguoiDung nd = new NguoiDung
            {
                HoTen = HoTen,
                Email = Email,
                MatKhau = MatKhau,         
                SDT = SDT,
                DiaChi = DiaChi,
                AnhDaiDien = avatar,
                MaVaiTro = 2              
            };

            ql.NguoiDungs.Add(nd);
            ql.SaveChanges();

            TempData["Success"] = "Đăng ký thành công! Vui lòng đăng nhập.";
            return RedirectToAction("Index", "DangNhap");
        }
    }
}

Template_DoAn_LTW/Controllers/DangNhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Template_DoAn_LTW.Controllers
{
    public class DangNhapController : Controller
    {
        QL_SachEntities ql = new QL_SachEntities();

        // GET: DangNhap
        public ActionResult Index()
        {
            ViewBag.Url = Url.Action("Index", "Book");
            return View();
        }
        [HttpPost]
        public ActionResult XulyFormDN(FormCollection form, string url)
        {
            string email = form["email"];
            string pass = form["password"];

            var kq = ql.NguoiDungs
                .FirstOrDefault(nd => nd.Email == email && nd.MatKhau == pass);

            if (kq != null)
            {
                FormsAuthentication.SetAuthCookie(kq.Email, true);

                Session["HoTen"] = kq.HoTen;
                Session["MaND"] = kq.MaND;
                Session["AnhDaiDien"] = kq.AnhDaiDien;

                return Redirect(url ?? Url.Action("Index", "Book"));
            }

            ViewBag.Error = "Tài khoản hoặc mật khẩu không đúng";
            ViewBag.Url = Url.Action("Index", "Book");
            return View("Index");
        }

        public ActionResult DangXuat()
        {
            Session.Clear();
            FormsAuthentication.SignOut();
            return Redirect("/");
        }
    }
}

Template_DoAn_LTW/Views/DangNhap/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_NewLayout.cshtml";
}

<div class="container">
    <div class="login-container nt-4" style="width: 400px; margin: auto">
        <div class="card shadow-lg p-3">
            <h3 class="card-title text-center fw-bold text-primary mb-0">Đăng nhập</h3>
            @using (Html.BeginForm("XulyFormDN", "DangNhap", new { url = ViewBag.Url }, FormMethod.Post))
            {
                <div class="mb-3">
                    <label for="loginEmail" class="form-label">Email</label>
                    <input type="email" name="email" class="form-control" id="loginEmail" required>
                </div>
                <div class="mb-3">
                    <label for="loginPassword" class="form-label">Mật Khẩu</label>
                    <input type="password" name="password" class="form-control" id="loginPassword" required>
                </div>
                <div class="mb-3">
                    <button type="submit" style="margin: 0;" class="btn btn-primary w-100 mb-3">ĐĂNG NHẬP</button>
                    <p class="text-center">
                        <a href="@Url.Action("Index", "DangKy")" class="text-decoration-none fw-bold">
                            Đăng ký ngay
                        </a>

                    </p>
                </div>
            }
        </div>
    </div>
</div>